FROM node:24-slim AS base

WORKDIR /app
ARG PNPM_Version=10.18.0
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable && corepack prepare pnpm@${PNPM_Version} --activate

FROM base AS prepare

RUN pnpm add turbo@^2 -g
COPY . .

RUN turbo prune web --docker


FROM base AS builder
# First install the dependencies (as they change less often)
COPY --from=prepare /app/out/json/ .
RUN pnpm install


FROM builder as Dev
COPY --from=prepare /app/out/full/ .

EXPOSE 5500


CMD ["pnpm", "web", "dev"]
