FROM node:24-slim AS base

WORKDIR /app
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

FROM base AS prepare

RUN pnpm add turbo@^2 -g
COPY . .

RUN turbo prune api --docker


FROM base AS builder
# First install the dependencies (as they change less often)
COPY --from=prepare /app/out/json/ .
RUN pnpm install
COPY --from=prepare /app/out/full/ .


CMD ["pnpm", "api", "dev"]
